export const GET_USER_ACCOUNT_REQ = "GET_USER_ACCOUNT_REQ";
export const GET_USER_ACCOUNT_SUCCESS = "GET_USER_ACCOUNT_SUCCESS";

export const APP_ERROR = "APP_ERROR";

export const LOAD_BLOCKCHAIN_DATA_REQ = "LOAD_BLOCKCHAIN_DATA_REQ";
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = "LOAD_BLOCKCHAIN_DATA_SUCCESS";

export const CREATE_TASKS_REQ = "CREATE_TASKS_REQ";
export const CREATE_TASKS_SUCCESS = "CREATE_TASKS_SUCCESS";

export const TOGGLE_TASKS_REQ = "TOGGLE_TASKS_REQ";
export const TOGGLE_TASKS_SUCCESS = "TOGGLE_TASKS_SUCCESS";

export const LIST_TASKS_REQ = "LIST_TASKS_REQ";
export const LIST_TASKS_SUCCESS = "LIST_TASKS_SUCCESS";
