export const GET_USER_ACCOUNT_REQ = "GET_USER_ACCOUNT_REQ";
export const GET_USER_ACCOUNT_SUCCESS = "GET_USER_ACCOUNT_SUCCESS";

export const APP_ERROR = "APP_ERROR";

export const LOAD_BLOCKCHAIN_DATA_REQ = "LOAD_BLOCKCHAIN_DATA_REQ";
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = "LOAD_BLOCKCHAIN_DATA_SUCCESS";

export const GET_VOTES_REQ = "ET_VOTES_REQ";
export const GET_VOTES_RES = "GET_VOTES_RES";

export const CAST_VOTE_REQ = "CAST_VOTE_REQ";
export const CAST_VOTE_RES = "CAST_VOTE_RES";
